### ISSUE TITLE
RoR group project: set up your Kanban board #17

### ISSUE THREAD

**Issue by MenendezON** [MenendezON/Recipe-app#12]
To see the project link, [click here](https://github.com/users/MenendezON/projects/1)

Members:
- @MenendezON 
- @malikhaiderkhan 
- @Wils-FOURR-speed

**Comment by DammyShittu** [comment]
Hi @MenendezON, @malikhaiderkhan and @Wils-FOURR-speed,

## Highlights
✔️ Assigned tasks

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add the tasks for these two.

  ![image](https://github.com/MenendezON/Recipe-app/assets/54848363/c5166581-a5af-42cc-81b9-a18fd78f2de4)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @MenendezON, @malikhaiderkhan and @Wils-FOURR-speed,

## APPROVED 🟢

## Highlights
✔️ Descriptive tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
